from models.resnet import *
from models.simple_CNN import *
from models.simple_CNN_EWC import *
from models.simple_CNN_fine_tune import *
from models.resnet_fine_tune import *
from models.simple_CNN_LWF import *
from models.simple_CNN_Ti_LWF import *
from models.resnet_LMRC import *
from models.resnet_Ti_LWF import *
from models.resnet_EWC import *
from models.resnet_LWF import *
